# This file contains values from Cookiecutter

default_context:
  project_name: "vkusvill-green-labels"
  package_name: "vkusvill_green_labels"
  git_platform: "github"
  username: "a1d4r"
  git_repo_url: "https://github.com/a1d4r/vkusvill-green-labels-notifier"
  python_version: "3.12"
  line_length: "100"
