version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vkusvill-green-labels-notifier:latest
    volumes:
      - ./vkusvill_green_labels:/app/vkusvill_green_labels
volumes:
  db-data: {}
  cache-data: {}
